### ISSUE TITLE
Champs à valeurs multiples

### ISSUE THREAD

**Issue by jmroyercom** [nikrou/rslt#3]
Prévoir un comportement du style "tags" pour les champs suivants : 
**Chanson > Nouvelle chanson**
* Auteur
* Compositeur
* Adaptateur
* Editeur
* Auteur éditeur
* Interprète
**Album > Nouvel album**
* Interprète

**Exemple : la chanson "Lorada"**
Auteur(s) : Gildas Arzel, Jacques Veneruso, Erick Benzi, Jean-Jacques Goldman
Compositeur(s) : Gildas Arzel, Jacques Veneruso, Erick Benzi, Jean-Jacques Goldman
Edition(s) : Editions J.R.G., Kevin Organisation 

Il faut considérer que chaque entrée séparée par une virgule est une valeur unique et non l'ensemble. Comme dans "tags", prévoir que le séparateur soit la virgule + un espace.

**Comment by nikrou** [comment]
Réglé en utilisant select2
