### ISSUE TITLE
Créer un groupe pour le plugin dans le menu côté gauche

### ISSUE THREAD

**Issue by jmroyercom** [nikrou/rslt#4]
A la manière de "Favoris", "Blogs" et "Plugins", créer un groupe "RSLT" comprenant les items suivants : 
* Actualités
* Albums
* Chansons
* Interprètes
* Médiathèque
* Pages
* Reprises
* Supports
* Paramètres

Cela pourrait ressembler à cela : 

![capture d ecran 2015-01-06 a 18 36 12](https://cloud.githubusercontent.com/assets/9936421/5632930/f2c65386-95d2-11e4-8e4a-b1c86c836a74.jpg)

**Comment by nikrou** [comment]
Super idée

**Comment by jmroyercom** [comment]
Note à moi-même : prévoir un set d'îcones pour ce menu.

**Comment by nikrou** [comment]
Fait.
