### ISSUE TITLE
version 2015.01.21 > Edition d'une chanson, problème affichage champs après enregistrement

### ISSUE THREAD

**Issue by jmroyercom** [nikrou/rslt#9]
Après modification de cette fiche :
- suppression de la valeur "Adaptateur"
- ajout de valeurs "Interprète"
- puis Enregistrer

On obtient cela : 
![capture d ecran 2015-01-21 a 22 40 00](https://cloud.githubusercontent.com/assets/9936421/5845787/392e0178-a1bf-11e4-89c0-f790e4283f93.jpg)

Malgré tout, les valeurs ont bien été prises en compte si on regarde par la vue "list".

A noter aussi que quand on quitte la page en ayant fait une modification mais sans enregistrer, on a pas de message d'erreur.

**Comment by nikrou** [comment]
Corrigé dans https://github.com/nikrou/rslt/commit/ac5d9c3c3e93e7477381551774e307116040433f

**Comment by jmroyercom** [comment]
- Les champs de saisie apparaissent à nouveau 
- mais les valeurs ont été remplacés par "undefined" dans la page d'édition de la fiche mais côté list, on a les bonnes valeurs.

![capture d ecran 2015-01-22 a 17 10 26](https://cloud.githubusercontent.com/assets/9936421/5859287/9d7249c4-a259-11e4-8bf8-566725d643ae.jpg)
![capture d ecran 2015-01-22 a 17 10 04](https://cloud.githubusercontent.com/assets/9936421/5859338/e6c36022-a259-11e4-8a5e-b22925165920.jpg)
